dataset_subdir: data_trajectories_bimanual/EnvMarvinTable-RobotMarvinBimanual-cooperative-v1
dataset_file_merged: dataset_merged.hdf5
robot_model: marvin_bimanual
task_family: cooperative
context_qs: true
context_ee_goal_pose: false
bspline_degree: 5
bspline_num_control_points_desired: 22
unet_input_dim: 32
batch_size: 128
results_dir: logs/marvin_bimanual/cooperative_v1
state_dim: 14
context_q_dim: 28
